# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: First_Job 
    steps:
    - bash: echo Build First_job
    - bash: echo $(PIPELINELEVELVARIABLE)
  - job: Second_job
    steps: 
    - bash: echo Second_job 
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo $(environment)DeployJob
- stage: QADeploy
  variables:
    environment: Dev
  dependsOn: Build 
  jobs: 
  - job: QADeployJob 
    steps:
    - bash: echo $(environment)DeployJob
- stage: ProdDeploy
  variables:
    environment: Dev
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps: 
    - bash: echo $(environment)DeployJob
  