trigger:
- main

# strategy:
#  matrix:
#    linux:
#      operatingSystem: ' ubuntu-latest'
#    mac:
#      operatingSystem: ' macos-latest' 


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - deployment: 
    environment: Build 
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo Ready To Build
- stage: Deployment
  jobs:
  - job: Dev
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to dev
  - job: FlowDev
  - deployment: FlowDevDeployJob
    environment: FlowDev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Flowdev 
- stage: QCDeploy
  jobs:
  - deployment: QCDeployJob
    environment: QC
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QC 
- stage: ProdDeploy
  jobs: 
  - deployment: ProdDeployJob
    environment: Prod
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to prod
  
