trigger:
- main

# strategy:
#  matrix:
#    linux:
#      operatingSystem: ' ubuntu-latest'
#    mac:
#      operatingSystem: ' macos-latest' 


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo " Do The Jobs:"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to dev
  - deployment: DevDeployJob2
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to dev 2
- stage: QCDeploy
  jobs:
  - deployment: QCDeployJob
    environment: QC
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QC 
- stage: ProdDeploy
  jobs: 
  - deployment: ProdDeployJob
    environment: Prod
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to prod
  
