trigger:
- main

# strategy:
#  matrix:
#    linux:
#      operatingSystem: ' ubuntu-latest'
#    mac:
#      operatingSystem: ' macos-latest' 


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - deployment: ON-BOARD
    environment: Build 
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo Ready To Build
- stage: Deployment
  jobs:
  - deployment: DevDeploy
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to dev
  - deployment: FlowDevDeploy
    environment: FlowDev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Flowdev 
- stage: QCDeploy
  jobs:
  - deployment: QCDeploy
    environment: QC
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QC 
- stage: ProdDeploy
  jobs: 
  - deployment: ProdDeploy
    environment: Prod
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to prod
  
